<a href="https://colab.research.google.com/github/loreelei/206/blob/main/Data_Prep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#  !pip install us

import pandas as pd

# prep

In [ ]:
us_states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming',
        '':''
}

# Choropleth and Scatter

In [ ]:
vac_df=pd.read_csv('/content/drive/MyDrive/STATS401/monthly_vac.csv')
fb_df=pd.read_csv('/content/drive/MyDrive/STATS401/facebook_sentiment.csv')
fb_df=fb_df.dropna(subset=['last_name'])
fb_df['date']=pd.to_datetime(fb_df['Post.Created.Date'])
fb_df['states']=fb_df.state.apply(lambda x:us_states[x])
vac_df=vac_df.iloc[:,1:]
vac_df.columns=['date','states','vac_percent']
vac_df['date']=pd.to_datetime(vac_df['date'])
pd.set_option('display.max_columns', 500)
fb_df.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (41,42,79,80,92,101) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Unnamed: 0,index,Unnamed: 0.1,facebook_correct,Page.Name,User.Name,Facebook.Id,Page.Category,Page.Admin.Top.Country,Page.Description,Page.Created,Likes.at.Posting,Followers.at.Posting,Post.Created,Post.Created.Date,Post.Created.Time,Type,Total.Interactions,Likes,Comments,Shares,Love,Wow,Haha,Sad,Angry,Care,Video.Share.Status,Is.Video.Owner.,Post.Views,Total.Views,Total.Views.For.All.Crossposts,Video.Length,URL,Message,Link,Final.Link,Image.Text,Link.Text,Description,Sponsor.Id,Sponsor.Name,Sponsor.Category,Overperforming.Score,id,Hedges,Impersonal.Pronoun,Swearing,Negation,Filler.Pause,Informal.Title,Formal.Title,Could.You,Can.You,By.The.Way,Let.Me.Know,Goodbye,For.Me,For.You,Reasoning,Reassurance,Ask.Agency,Give.Agency,Hello,Please,First.Person.Plural,First.Person.Single,Second.Person,Positive.Emotion,Negative.Emotion,Questions,Gratitude,Apology,Truth.Intensifier,receptiveness,warmth,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,district,senate_class,party,url,address,phone,contact_form,rss_url,twitter,facebook,youtube,youtube_id,bioguide_id,thomas_id,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id,birthdate,birthyear,Optimistic,Thankful,Empathetic,Pessimistic,Anxious,Sad.1,Annoyed,Denial,Official report,Surprise,Joking,Message.1,date,states
0,0,48,49,NaN,Congressman Devin Nunes,NaN,3.764704e+11,GOVERNMENT_OFFICIAL,NaN,Official Facebook page for Congressman Devin N...,2010-03-18 19:20:55,76232.0,82494.0,2021-07-27,2021-07-27,11H 18M 36S,Link,1483.0,1177.0,113.0,88.0,80.0,5.0,11.0,1.0,6.0,2.0,NaN,-,0.0,0.0,0.0,NaN,https://www.facebook.com/376470350795/posts/10...,"In case you missed it, I recently authored the...",https://sjvsun.com/california/nunes-pushing-to...,NaN,NaN,Nunes pushing to save Diablo Canyon amid two d...,"The senior Republican, who has routinely led s...",NaN,NaN,NaN,3.86,388974,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,1,8,5,0,0,0,0,-0.091795,0.920020,Carey,Mike,NaN,NaN,NaN,NaN,1971-03-13,M,rep,OH,15.0,NaN,Republican,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C001126,NaN,NaN,NaN,H2OH15228,NaN,456864.0,NaN,NaN,NaN,NaN,Mike Carey (politician),1971-03-13,1971.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,"In case you missed it, I recently authored the...",2021-07-27,Ohio
1,1,168,169,NaN,Congressman Devin Nunes,NaN,3.764704e+11,GOVERNMENT_OFFICIAL,NaN,Official Facebook page for Congressman Devin N...,2010-03-18 19:20:55,76162.0,82422.0,2021-08-16,2021-08-16,17H 9M 39S,Status,2667.0,1448.0,266.0,520.0,15.0,9.0,4.0,209.0,180.0,16.0,NaN,-,0.0,0.0,0.0,NaN,https://www.facebook.com/376470350795/posts/10...,President Bidenâ€™s disastrous withdrawal from...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.91,376942,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3,1,3,1,3,0,0,0,0,-0.610464,0.065044,Carey,Mike,NaN,NaN,NaN,NaN,1971-03-13,M,rep,OH,15.0,NaN,Republican,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C001126,NaN,NaN,NaN,H2OH15228,NaN,456864.0,NaN,NaN,NaN,NaN,Mike Carey (politician),1971-03-13,1971.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,President Bidenâ€™s disastrous withdrawal from...,2021-08-16,Ohio
2,2,228,229,NaN,Congressman Devin Nunes,NaN,3.764704e+11,GOVERNMENT_OFFICIAL,NaN,Official Facebook page for Congressman Devin N...,2010-03-18 19:20:55,76232.0,82494.0,2021-07-27,2021-07-27,13H 30M 58S,Link,743.0,518.0,105.0,37.0,71.0,2.0,3.0,0.0,0.0,7.0,NaN,-,0.0,0.0,0.0,NaN,https://www.facebook.com/376470350795/posts/10...,House Republicans rally for freedom for the Cu...,https://rumble.com/vke8bt-cuba-libre.html,NaN,NaN,Cuba Libre,House Republicans rally for freedom for the Cu...,NaN,NaN,NaN,1.93,388842,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,-0.208411,0.116494,Carey,Mike,NaN,NaN,NaN,NaN,1971-03-13,M,rep,OH,15.0,NaN,Republican,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C001126,NaN,NaN,NaN,H2OH15228,NaN,456864.0,NaN,NaN,NaN,NaN,Mike Carey (politician),1971-03-13,1971.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,House Republicans rally for freedom for the Cu...,2021-07-27,Ohio
3,3,270,271,NaN,Congressman Devin Nunes,NaN,3.764704e+11,GOVERNMENT_OFFICIAL,NaN,Official Facebook page for Congressman Devin N...,2010-03-18 19:20:55,75807.0,82058.0,2021-10-26,2021-10-26,10H 34M 25S,Link,591.0,394.0,67.0,89.0,12.0,6.0,1.0,1.0,20.0,1.0,NaN,-,0.0,0.0,0.0,NaN,https://www.facebook.com/376470350795/posts/10...,LIVE SOON: Ways and Means Republicans fight ba...,https://rumble.com/vo8g85-gop-expose-bidens-pl...,NaN,NaN,GOP Expose Bidenâ€™s Planned IRS Surveillance ...,"WATCH LIVE: Tuesday, October 26, 2021 at 11:00...",NaN,NaN,NaN,1.56,339275,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.527811,0.076272,Carey,Mike,NaN,NaN,NaN,NaN,1971-03-13,M,rep,OH,15.0,NaN,Republican,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C001126,NaN,NaN,NaN,H2OH15228,NaN,456864.0,NaN,NaN,NaN,NaN,Mike Carey (politician),1971-03-13,1971.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,LIVE SOON: Ways and Means Republicans fight ba...,2021-10-26,Ohio
4,4,354,355,NaN,Congressman Devin Nunes,NaN,3.764704e+11,GOVERNMENT_OFFICIAL,NaN,Official Facebook page for Congressman Devin N...,2010-03-18 19:20:55,73913.0,80163.0,2021-04-01,2021-04-01,12H 45M 19S,Link,1604.0,951.0,189.0,180.0,8.0,11.0,18.0,51.0,193.0,3.0,NaN,-,0.0,0.0,0.0,NaN,https://www.facebook.com/376470350795/posts/10...,"In case you missed it, I recently spoke with M...",https://rumble.com/vf7dgt-nunes-biden-stopped-...,NaN,NaN,"Nunes: Biden stopped border wall construction,...",Congressman Devin Nunes discusses President Bi...,NaN,NaN,NaN,4.18,456952,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,3,0,0,0,0,-0.297488,0.093649,Carey,Mike,NaN,NaN,NaN,NaN,1971-03-13,M,rep,OH,15.0,NaN,Republican,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C001126,NaN,NaN,NaN,H2OH15228,NaN,456864.0,NaN,NaN,NaN,NaN,Mike Carey (politician),1971-03-13,1971.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,"In case you missed it, I recently spoke with M...",2021-04-01,Ohio

In [ ]:
sent_sum=fb_df.groupby([fb_df.date.dt.month,fb_df.states,]).count().iloc[:,-13:-2]
sent_sum.columns=[s + '_sum' for s in sent_sum.columns]
sent_sum
month=[1,2,3,4,5,6,7,8,9,10,11]*50
month.sort()

In [ ]:
# fb_df[['date','states']].drop_duplicates()
# vac_df[['date','states']].drop_duplicates()
# fb_df.date.value_counts()
# vac_df.date.value_counts()
sent_sum=fb_df.groupby([fb_df.date.dt.month,fb_df.states,]).sum().iloc[:,-11:]
sent_sum.columns=[s + '_sum' for s in sent_sum.columns]
sent_sum['date']=month
sent_sum['states']=sent_sum.index.get_level_values('states')
sent_sum.index=range(550)
sent_count=fb_df.groupby([fb_df.date.dt.month,fb_df.states,]).count().iloc[:,-13:-2]
sent_count.columns=[s + '_count' for s in sent_count.columns]
sent_count['date']=month
sent_count['states']=sent_count.index.get_level_values('states')
sent_count.index=range(550)

vac_rt=vac_df.groupby([vac_df.date.dt.month,vac_df.states]).mean().reset_index()

In [ ]:
temp=sent_count.merge(sent_sum,on=['date','states'],how='left')
final=temp.merge(vac_rt,on=['date','states'],how='left')
final

,Optimistic_count,Thankful_count,Empathetic_count,Pessimistic_count,Anxious_count,Sad.1_count,Annoyed_count,Denial_count,Official report_count,Surprise_count,Joking_count,date,states,Optimistic_sum,Thankful_sum,Empathetic_sum,Pessimistic_sum,Anxious_sum,Sad.1_sum,Annoyed_sum,Denial_sum,Official report_sum,Surprise_sum,Joking_sum,vac_percent
0,73,73,73,73,73,73,73,73,73,73,73,1,Alabama,47.0,21.0,4.0,0.0,3.0,0.0,18.0,0.0,9.0,6.0,10.0,24.375
1,48,48,48,48,48,48,48,48,48,48,48,1,Alaska,33.0,21.0,0.0,0.0,3.0,1.0,10.0,2.0,9.0,4.0,2.0,29.270
2,130,130,130,130,130,130,130,130,130,130,130,1,Arizona,78.0,42.0,1.0,1.0,5.0,10.0,22.0,0.0,19.0,20.0,13.0,29.230
3,53,53,53,53,53,53,53,53,53,53,53,1,Arkansas,24.0,22.0,5.0,0.0,0.0,0.0,16.0,1.0,9.0,6.0,2.0,26.350
4,913,913,913,913,913,913,913,913,913,913,913,1,California,541.0,252.0,11.0,16.0,50.0,42.0,185.0,13.0,163.0,110.0,97.0,34.745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,112,112,112,112,112,112,112,112,112,112,112,11,Virginia,76.0,38.0,1.0,1.0,3.0,3.0,11.0,0.0,20.0,15.0,9.0,64.120
546,153,153,153,153,153,153,153,153,153,153,153,11,Washington,105.0,58.0,3.0,6.0,14.0,2.0,31.0,1.0,14.0,16.0,12.0,64.390
547,70,70,70,70,70,70,70,70,70,70,70,11,West Virginia,33.0,24.0,2.0,3.0,8.0,1.0,22.0,1.0,7.0,4.0,3.0,41.460
548,85,85,85,85,85,85,85,85,85,85,85,11,Wisconsin,60.0,26.0,2.0,1.0,4.0,2.0,17.0,1.0,12.0,5.0,10.0,58.980
549,30,30,30,30,30,30,30,30,30,30,30,11,Wyoming,13.0,5.0,0.0,2.0,3.0,4.0,11.0,0.0,2.0,3.0,7.0,44.970

In [ ]:
for sent in fb_df.iloc[:,-14:-3].columns:
  final[sent+'_rate']=final[sent+'_sum']/final[sent+'_count']

In [ ]:
cols = list(final.columns)
cols.sort()
final[cols].to_csv('/content/drive/MyDrive/STATS401/plot1.csv')

# Time RIver

Date(Month-Year)	State	党派	Post数量(这个州在这个月的post数量)

In [ ]:
sum=fb_df.groupby([fb_df.date.dt.month,fb_df.states,fb_df.party]).sum().iloc[:,-11:].reindex()
count=fb_df.groupby([fb_df.date.dt.month,fb_df.states,fb_df.party]).count().iloc[:,-13:-2].reindex()

In [ ]:
sum.columns=[s + '_sum' for s in sum.columns]
count.columns=[s + '_count' for s in count.columns]

In [ ]:
tr_final=count.merge(sum, left_index=True, right_on=['date', 'states','party'])

In [ ]:
tr_final=count.merge(sum, left_index=True, right_on=['date', 'states','party'])

for sent in fb_df.iloc[:,-14:-3].columns:
  tr_final[sent+'_rate']=tr_final[sent+'_sum']/tr_final[sent+'_count']

In [ ]:
cols = list(tr_final.columns)
cols.sort()
tr_final[cols].to_csv('/content/drive/MyDrive/STATS401/time_river.csv')

In [ ]:
tr_final

                               Optimistic_count  Thankful_count  \
date states        party
1    Alabama       Democrat                  34              34
                   Republican                39              39
     Alaska        Republican                48              48
     Arizona       Democrat                 113             113
                   Republican                17              17
...                                         ...             ...
11   West Virginia Democrat                  15              15
                   Republican                55              55
     Wisconsin     Democrat                  61              61
                   Republican                24              24
     Wyoming       Republican                30              30

                               Empathetic_count  Pessimistic_count  \
date states        party
1    Alabama       Democrat                  34                 34
                   Republican                39                 39
     Alaska        Republican                48                 48
     Arizona       Democrat                 113                113
                   Republican                17                 17
...                                         ...                ...
11   West Virginia Democrat                  15                 15
                   Republican                55                 55
     Wisconsin     Democrat                  61                 61
                   Republican                24                 24
     Wyoming       Republican                30                 30

                               Anxious_count  Sad.1_count  Annoyed_count  \
date states        party
1    Alabama       Democrat               34           34             34
                   Republican             39           39             39
     Alaska        Republican             48           48             48
     Arizona       Democrat              113          113            113
                   Republican             17           17             17
...                                      ...          ...            ...
11   West Virginia Democrat               15           15             15
                   Republican             55           55             55
     Wisconsin     Democrat               61           61             61
                   Republican             24           24             24
     Wyoming       Republican             30           30             30

                               Denial_count  Official report_count  \
date states        party
1    Alabama       Democrat              34                     34
                   Republican            39                     39
     Alaska        Republican            48                     48
     Arizona       Democrat             113                    113
                   Republican            17                     17
...                                     ...                    ...
11   West Virginia Democrat              15                     15
                   Republican            55                     55
     Wisconsin     Democrat              61                     61
                   Republican            24                     24
     Wyoming       Republican            30                     30

                               Surprise_count  Joking_count  Optimistic_sum  \
date states        party
1    Alabama       Democrat                34            34            24.0
                   Republican              39            39            23.0
     Alaska        Republican              48            48            33.0
     Arizona       Democrat               113           113            69.0
                   Republican              17            17             9.0
...                                       ...           ...             ...
11   West Virginia Democrat                15            15             9.0
                   Republican              55            55            24.0
     Wisconsin     Democrat                61            61            45.0
                   Republican              24            24            15.0
     Wyoming       Republican              30            30            13.0

                               Thankful_sum  Empathetic_sum  Pessimistic_sum  \
date states        party
1    Alabama       Democrat             7.0             2.0              0.0
                   Republican          14.0             2.0              0.0
     Alaska        Republican          21.0             0.0              0.0
     Arizona       Democrat            38.0             1.0              1.0
                   Republican           4.0             0.0              0.0
...                                     ...             ...              ...
11   West Virginia Democrat             7.0             1.0              0.0
                   Republican          17.0             1.0              3.0
     Wisconsin     Democrat            15.0             2.0              1.0
                   Republican          11.0             0.0              0.0
     Wyoming       Republican           5.0             0.0              2.0

                               Anxious_sum  Sad.1_sum  Annoyed_sum  \
date states        party
1    Alabama       Democrat            2.0        0.0          4.0
                   Republican          1.0        0.0         14.0
     Alaska        Republican          3.0        1.0         10.0
     Arizona       Democrat            5.0        8.0         20.0
                   Republican          0.0        2.0          2.0
...                                    ...        ...          ...
11   West Virginia Democrat            2.0        0.0          2.0
                   Republican          6.0        1.0         20.0
     Wisconsin     Democrat            1.0        2.0         13.0
                   Republican          3.0        0.0          4.0
     Wyoming       Republican          3.0        4.0         11.0

                               Denial_sum  Official report_sum  Surprise_sum  \
date states        party
1    Alabama       Democrat           0.0                  6.0           4.0
                   Republican         0.0                  3.0           2.0
     Alaska        Republican         2.0                  9.0           4.0
     Arizona       Democrat           0.0                 16.0          16.0
                   Republican         0.0                  3.0           4.0
...                                   ...                  ...           ...
11   West Virginia Democrat           0.0                  3.0           0.0
                   Republican         1.0                  4.0           4.0
     Wisconsin     Democrat           0.0                  7.0           2.0
                   Republican         1.0                  5.0           3.0
     Wyoming       Republican         0.0                  2.0           3.0

                               Joking_sum  Optimistic_rate  Thankful_rate  \
date states        party
1    Alabama       Democrat           7.0         0.705882       0.205882
                   Republican         3.0         0.589744       0.358974
     Alaska        Republican         2.0         0.687500       0.437500
     Arizona       Democrat           9.0         0.610619       0.336283
                   Republican         4.0         0.529412       0.235294
...                                   ...              ...            ...
11   West Virginia Democrat           1.0         0.600000       0.466667
                   Republican         2.0         0.436364       0.309091
     Wisconsin     Democrat           7.0         0.737705       0.245902
                   Republican         3.0         0.625000       0.458333
     Wyoming       Republican         7.0         0.433333       0.166667

                               Empathetic_rate  Pessimistic_rate  \
date states        party
1    Alabama       Democrat           0.058824          0.000000
                   Republican         0.051282          0.000000
     Alaska        Republican         0.000000          0.000000
     Arizona       Democrat           0.008850          0.008850
                   Republican         0.000000          0.000000
...                                        ...               ...
11   West Virginia Democrat           0.066667          0.000000
                   Republican         0.018182          0.054545
     Wisconsin     Democrat           0.032787          0.016393
                   Republican         0.000000          0.000000
     Wyoming       Republican         0.000000          0.066667

                               Anxious_rate  Sad.1_rate  Annoyed_rate  \
date states        party
1    Alabama       Democrat        0.058824    0.000000      0.117647
                   Republican      0.025641    0.000000      0.358974
     Alaska        Republican      0.062500    0.020833      0.208333
     Arizona       Democrat        0.044248    0.070796      0.176991
                   Republican      0.000000    0.117647      0.117647
...                                     ...         ...           ...
11   West Virginia Democrat        0.133333    0.000000      0.133333
                   Republican      0.109091    0.018182      0.363636
     Wisconsin     Democrat        0.016393    0.032787      0.213115
                   Republican      0.125000    0.000000      0.166667
     Wyoming       Republican      0.100000    0.133333      0.366667

                               Denial_rate  Official report_rate  \
date states        party
1    Alabama       Democrat       0.000000              0.176471
                   Republican     0.000000              0.076923
     Alaska        Republican     0.041667              0.187500
     Arizona       Democrat       0.000000              0.141593
                   Republican     0.000000              0.176471
...                                    ...                   ...
11   West Virginia Democrat       0.000000              0.200000
                   Republican     0.018182              0.072727
     Wisconsin     Democrat       0.000000              0.114754
                   Republican     0.041667              0.208333
     Wyoming       Republican     0.000000              0.066667

                               Surprise_rate  Joking_rate
date states        party
1    Alabama       Democrat         0.117647     0.205882
                   Republican       0.051282     0.076923
     Alaska        Republican       0.083333     0.041667
     Arizona       Democrat         0.141593     0.079646
                   Republican       0.235294     0.235294
...                                      ...          ...
11   West Virginia Democrat         0.000000     0.066667
                   Republican       0.072727     0.036364
     Wisconsin     Democrat         0.032787     0.114754
                   Republican       0.125000     0.125000
     Wyoming       Republican       0.100000     0.233333

[877 rows x 33 columns]

#Circular Plot
Congressman Name	State	num of sad	num of anxious	num of thankful
		以州为单位，这个州在这个月：属于sad的post个数	以州为单位，这个州在这个月：属于anxious的post个数	以州为单位，这个州在这个月：属于sad的thankful个数

In [ ]:
sentiments=fb_df.iloc[:,-14:-3].columns.to_list()
col_list=sentiments+['first_name','last_name','party','states','Page.Name']
sum=fb_df.groupby([fb_df.first_name, fb_df.last_name,fb_df.party, fb_df.states, fb_df['Page.Name']]).sum()[sentiments]
count=fb_df.groupby([fb_df.first_name, fb_df.last_name,fb_df.party, fb_df.states, fb_df['Page.Name']]).count()[sentiments]
sum.columns=[s + '_sum' for s in sum.columns]
count.columns=[s + '_count' for s in count.columns]

In [ ]:
cp_final=count.merge(sum, left_index=True, right_on=['first_name','last_name','party','states','Page.Name'])

for sent in fb_df.iloc[:,-14:-3].columns:
  cp_final[sent+'_rate']=cp_final[sent+'_sum']/cp_final[sent+'_count']

In [ ]:
cp_final

                                                                                 Optimistic_count  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                            156
           Schiff    Democrat   California     Congressman Adam Schiff                        313
           Smith     Democrat   Washington     Rep. Adam Smith                                343
Adrian     Smith     Republican Nebraska       Adrian Smith                                     6
Al         Green     Democrat   Texas          Rep. Al Green                                  203
...                                                                                           ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                      227
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler                   426
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                             309
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating               103
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                      93

                                                                                 Thankful_count  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                          156
           Schiff    Democrat   California     Congressman Adam Schiff                      313
           Smith     Democrat   Washington     Rep. Adam Smith                              343
Adrian     Smith     Republican Nebraska       Adrian Smith                                   6
Al         Green     Democrat   Texas          Rep. Al Green                                203
...                                                                                         ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                    227
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler                 426
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                           309
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating             103
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                    93

                                                                                 Empathetic_count  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                            156
           Schiff    Democrat   California     Congressman Adam Schiff                        313
           Smith     Democrat   Washington     Rep. Adam Smith                                343
Adrian     Smith     Republican Nebraska       Adrian Smith                                     6
Al         Green     Democrat   Texas          Rep. Al Green                                  203
...                                                                                           ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                      227
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler                   426
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                             309
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating               103
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                      93

                                                                                 Pessimistic_count  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                             156
           Schiff    Democrat   California     Congressman Adam Schiff                         313
           Smith     Democrat   Washington     Rep. Adam Smith                                 343
Adrian     Smith     Republican Nebraska       Adrian Smith                                      6
Al         Green     Democrat   Texas          Rep. Al Green                                   203
...                                                                                            ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                       227
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler                    426
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                              309
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating                103
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                       93

                                                                                 Anxious_count  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                         156
           Schiff    Democrat   California     Congressman Adam Schiff                     313
           Smith     Democrat   Washington     Rep. Adam Smith                             343
Adrian     Smith     Republican Nebraska       Adrian Smith                                  6
Al         Green     Democrat   Texas          Rep. Al Green                               203
...                                                                                        ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                   227
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler                426
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                          309
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating            103
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                   93

                                                                                 Sad.1_count  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                       156
           Schiff    Democrat   California     Congressman Adam Schiff                   313
           Smith     Democrat   Washington     Rep. Adam Smith                           343
Adrian     Smith     Republican Nebraska       Adrian Smith                                6
Al         Green     Democrat   Texas          Rep. Al Green                             203
...                                                                                      ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                 227
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler              426
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                        309
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating          103
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                 93

                                                                                 Annoyed_count  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                         156
           Schiff    Democrat   California     Congressman Adam Schiff                     313
           Smith     Democrat   Washington     Rep. Adam Smith                             343
Adrian     Smith     Republican Nebraska       Adrian Smith                                  6
Al         Green     Democrat   Texas          Rep. Al Green                               203
...                                                                                        ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                   227
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler                426
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                          309
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating            103
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                   93

                                                                                 Denial_count  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                        156
           Schiff    Democrat   California     Congressman Adam Schiff                    313
           Smith     Democrat   Washington     Rep. Adam Smith                            343
Adrian     Smith     Republican Nebraska       Adrian Smith                                 6
Al         Green     Democrat   Texas          Rep. Al Green                              203
...                                                                                       ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                  227
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler               426
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                         309
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating           103
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                  93

                                                                                 Official report_count  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                                 156
           Schiff    Democrat   California     Congressman Adam Schiff                             313
           Smith     Democrat   Washington     Rep. Adam Smith                                     343
Adrian     Smith     Republican Nebraska       Adrian Smith                                          6
Al         Green     Democrat   Texas          Rep. Al Green                                       203
...                                                                                                ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                           227
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler                        426
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                                  309
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating                    103
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                           93

                                                                                 Surprise_count  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                          156
           Schiff    Democrat   California     Congressman Adam Schiff                      313
           Smith     Democrat   Washington     Rep. Adam Smith                              343
Adrian     Smith     Republican Nebraska       Adrian Smith                                   6
Al         Green     Democrat   Texas          Rep. Al Green                                203
...                                                                                         ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                    227
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler                 426
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                           309
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating             103
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                    93

                                                                                 Joking_count  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                        156
           Schiff    Democrat   California     Congressman Adam Schiff                    313
           Smith     Democrat   Washington     Rep. Adam Smith                            343
Adrian     Smith     Republican Nebraska       Adrian Smith                                 6
Al         Green     Democrat   Texas          Rep. Al Green                              203
...                                                                                       ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                  227
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler               426
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                         309
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating           103
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                  93

                                                                                 Optimistic_sum  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                         93.0
           Schiff    Democrat   California     Congressman Adam Schiff                    178.0
           Smith     Democrat   Washington     Rep. Adam Smith                            254.0
Adrian     Smith     Republican Nebraska       Adrian Smith                                 4.0
Al         Green     Democrat   Texas          Rep. Al Green                               83.0
...                                                                                         ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                   61.0
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler               158.0
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                          80.0
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating            66.0
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                  41.0

                                                                                 Thankful_sum  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                       50.0
           Schiff    Democrat   California     Congressman Adam Schiff                   52.0
           Smith     Democrat   Washington     Rep. Adam Smith                          133.0
Adrian     Smith     Republican Nebraska       Adrian Smith                               0.0
Al         Green     Democrat   Texas          Rep. Al Green                             36.0
...                                                                                       ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                 51.0
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler              91.0
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                        49.0
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating          40.0
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                27.0

                                                                                 Empathetic_sum  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                          8.0
           Schiff    Democrat   California     Congressman Adam Schiff                      2.0
           Smith     Democrat   Washington     Rep. Adam Smith                              4.0
Adrian     Smith     Republican Nebraska       Adrian Smith                                 1.0
Al         Green     Democrat   Texas          Rep. Al Green                                6.0
...                                                                                         ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                    4.0
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler                15.0
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                          13.0
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating             3.0
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                   0.0

                                                                                 Pessimistic_sum  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                           2.0
           Schiff    Democrat   California     Congressman Adam Schiff                       2.0
           Smith     Democrat   Washington     Rep. Adam Smith                               1.0
Adrian     Smith     Republican Nebraska       Adrian Smith                                  0.0
Al         Green     Democrat   Texas          Rep. Al Green                                 3.0
...                                                                                          ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                     2.0
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler                  8.0
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                            3.0
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating              1.0
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                    1.0

                                                                                 Anxious_sum  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                      10.0
           Schiff    Democrat   California     Congressman Adam Schiff                  32.0
           Smith     Democrat   Washington     Rep. Adam Smith                           9.0
Adrian     Smith     Republican Nebraska       Adrian Smith                              1.0
Al         Green     Democrat   Texas          Rep. Al Green                             5.0
...                                                                                      ...
Vern       Buchanan  Republican Florida        Congressman Vern Buchanan                27.0
Vicky      Hartzler  Republican Missouri       Congresswoman Vicky Hartzler             56.0
Virginia   Foxx      Republican North Carolina Rep. Virginia Foxx                       11.0
William    Keating   Democrat   Massachusetts  U.S. Representative Bill Keating          4.0
Zoe        Lofgren   Democrat   California     Representative Zoe Lofgren                5.0

                                                                                 Sad.1_sum  \
first_name last_name party      states         Page.Name
Adam       Kinzinger Republican Illinois       Rep. Adam Kinzinger                     6.0
           Schiff    Democrat   California     Congressman Adam Schiff                31.0
           Smith     Democrat   Washington     Rep. Adam Smith                        14.0
Adrian     Smith     Republican Nebraska       Adrian Smith                            0.0

In [ ]:
cols = list(cp_final.columns)
cols.sort()
cp_final[cols].to_csv('/content/drive/MyDrive/STATS401/circular_plot.csv')

#spider

性别	种族	党派	年龄	Wold	Frequency	Number of Post(一共有多少post)

In [ ]:
sentiments=fb_df.iloc[:,-14:-3].columns.to_list()
col_list=sentiments+['gender','type','party']
sum=fb_df.groupby([fb_df.gender, fb_df.type,fb_df.party]).sum()[sentiments]
count=fb_df.groupby([fb_df.gender, fb_df.type,fb_df.party]).count()[sentiments]
sum.columns=[s + '_sum' for s in sum.columns]
count.columns=[s + '_count' for s in count.columns]

In [ ]:
sp_final=count.merge(sum, left_index=True, right_on=['gender','type','party'])

for sent in fb_df.iloc[:,-14:-3].columns:
  sp_final[sent+'_rate']=sp_final[sent+'_sum']/sp_final[sent+'_count']

In [ ]:
cols = list(sp_final.columns)
cols.sort()
sp_final[cols].to_csv('/content/drive/MyDrive/STATS401/spider_plot.csv')

# word cloud

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/STATS401/facebook_sentiment.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (41,42,79,80,92,101) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
df_stats = df.groupby(['gender', 'party']).agg(['mean', 'median', 'std'])
df_stats.columns = ["_".join(x) for x in df_stats.columns.ravel()]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.

In [ ]:
df_stats.columns[-50:-10]

Index(['cspan_id_median', 'cspan_id_std', 'govtrack_id_mean',
       'govtrack_id_median', 'govtrack_id_std', 'votesmart_id_mean',
       'votesmart_id_median', 'votesmart_id_std', 'washington_post_id_mean',
       'washington_post_id_median', 'washington_post_id_std', 'icpsr_id_mean',
       'icpsr_id_median', 'icpsr_id_std', 'birthyear_mean', 'birthyear_median',
       'birthyear_std', 'Optimistic_mean', 'Optimistic_median',
       'Optimistic_std', 'Thankful_mean', 'Thankful_median', 'Thankful_std',
       'Empathetic_mean', 'Empathetic_median', 'Empathetic_std',
       'Pessimistic_mean', 'Pessimistic_median', 'Pessimistic_std',
       'Anxious_mean', 'Anxious_median', 'Anxious_std', 'Sad.1_mean',
       'Sad.1_median', 'Sad.1_std', 'Annoyed_mean', 'Annoyed_median',
       'Annoyed_std', 'Denial_mean', 'Denial_median'],
      dtype='object')

In [ ]:
x=df_stats[['Likes.at.Posting_mean', 'Followers.at.Posting_mean','Optimistic_mean', 'Thankful_mean',  'Pessimistic_mean', 'Annoyed_mean', ]].T

x.to_csv('/content/drive/MyDrive/STATS401/summary.csv')

In [ ]:
pd.set_option('display.max_columns', 500)

df.describe(include='all')

,Unnamed: 0,facebook_correct,Page.Name,User.Name,Facebook.Id,Page.Category,Page.Admin.Top.Country,Page.Description,Page.Created,Likes.at.Posting,Followers.at.Posting,Post.Created,Post.Created.Date,Post.Created.Time,Type,Total.Interactions,Likes,Comments,Shares,Love,Wow,Haha,Sad,Angry,Care,Video.Share.Status,Is.Video.Owner.,Post.Views,Total.Views,Total.Views.For.All.Crossposts,Video.Length,URL,Message,Link,Final.Link,Image.Text,Link.Text,Description,Sponsor.Id,Sponsor.Name,Sponsor.Category,Overperforming.Score,id,Hedges,Impersonal.Pronoun,Swearing,Negation,Filler.Pause,Informal.Title,Formal.Title,Could.You,Can.You,By.The.Way,Let.Me.Know,Goodbye,For.Me,For.You,Reasoning,Reassurance,Ask.Agency,Give.Agency,Hello,Please,First.Person.Plural,First.Person.Single,Second.Person,Positive.Emotion,Negative.Emotion,Questions,Gratitude,Apology,Truth.Intensifier,receptiveness,warmth,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,district,senate_class,party,url,address,phone,contact_form,rss_url,twitter,facebook,youtube,youtube_id,bioguide_id,thomas_id,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id,birthdate,birthyear
count,650362.000000,649306,650362,649306,6.503320e+05,650332,645385,650332,650332,6.503160e+05,6.478810e+05,650332,650332,650332,650332,6.503320e+05,6.503320e+05,650332.000000,650332.000000,650332.000000,650332.000000,650332.000000,650332.000000,650332.000000,650332.000000,101550,650332,6.503320e+05,6.503320e+05,6.503320e+05,0.0,650332,616118,576195,53754,56879,409541,279302,4.800000e+01,38,38,650328.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.00000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,650362.000000,6.503620e+05,398225,398225,190914,20054,44481,397873,398225,398225,398225,398225,275777.000000,122448.000000,398225,397873,397873,397873,122448,285328,392811,379757,307179,374108,398225,390802.000000,397873,122448,398225,3.940720e+05,398225.000000,395856.000000,396170,0.0,395856.000000,398225,398225,398225.000000
unique,NaN,624,625,624,NaN,12,7,608,624,NaN,NaN,633960,1097,64107,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,NaN,NaN,NaN,NaN,642404,598514,527685,49201,47472,248632,221143,NaN,34,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,279,189,42,4,23,298,296,2,2,50,NaN,NaN,3,298,298,298,74,229,292,282,238,282,300,NaN,298,74,300,NaN,NaN,NaN,296,NaN,NaN,300,296,NaN
top,NaN,DonaldTrump,Donald J. Trump,DonaldTrump,NaN,GOVERNMENT_OFFICIAL,US,Government Official,2009-04-08 00:17:56,NaN,NaN,2019-05-11 10:00:01,2020-05-11,9H 0M 1S,Link,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,owned,-,NaN,NaN,NaN,NaN,https://www.facebook.com/376470350795/posts/10...,Please SHARE!,https://www.irs.gov/coronavirus/non-filers-ent...,https://www.healthcare.gov/,VETERANS DAY HONORING ALL WHO SERVED,Timeline Photos,The Official U.S. Senate website of Senator Jo...,NaN,Broadnet,NON_PROFIT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sanders,John,M.,Jr.,Chuck,Bernard Sanders,1941-09-08,M,rep,CA,NaN,NaN,Democrat,https://www.sanders.senate.gov,332 Dirksen Senate Office Building Washington ...,202-224-5141,https://www.sanders.senate.gov/contact/,http://www.sanders.senate.gov/rss/,SenSanders,senatorsanders,senatorsanders,UCD_DaKNac0Ta-2PeHuoQ1uA,S000033,NaN,N00000528,S313,"H8VT01016,S4VT00033",NaN,NaN,NaN,Bernie Sanders,NaN,NaN,Bernie Sanders,1941-09-08,NaN
freq,NaN,9641,9641,9641,NaN,371837,643064,10484,9641,NaN,NaN,12,1698,480,242198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79845,549742,NaN,NaN,NaN,NaN,12,284,331,161,89,12183,624,NaN,3,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6375,16284,22057,16347,8897,6375,6375,294174,275777,50030,NaN,NaN,230088,6375,6375,6375,6375,6375,6375,6375,6375,6375,6375,NaN,6375,6375,6375,NaN,NaN,NaN,6375,NaN,NaN,6375,6375,NaN
mean,325181.500000,NaN,NaN,NaN,1.834656e+14,NaN,NaN,NaN,NaN,6.022107e+05,6.561463e+05,NaN,NaN,NaN,NaN,2.800555e+03,1.618607e+03,414.441292,274.964174,266.122750,16.367435,55.329244,38.712651,99.704257,16.306161,NaN,NaN,4.954098e+03,1.781011e+04,4.667424e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.454986e+14,NaN,NaN,-9.526304,324836.771487,0.187362,1.697565,0.003241,0.293724,0.001668,0.054091,0.020339,0.000454,0.002186,0.000235,0.000660,0.000575,0.006690,0.005065,0.062973,0.000738,0.002928,0.029436,0.002897,0.041214,1.077386,0.68135,0.376927,2.310965,1.239639,0.084012,0.124006,0.003234,0.013167,-0.214182,2.109165e-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.872259,1.989596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1767.969908,NaN,NaN,NaN,5.445803e+05,402862.396756,50907.720105,NaN,NaN,25299.840078,NaN,NaN,1956.853364
std,187743.482222,NaN,NaN,NaN,6.366737e+14,NaN,NaN,NaN,NaN,3.360301e+06,3.582184e+06,NaN,NaN,NaN,NaN,2.649110e+04,1.669512e+04,3680.391013,2910.460834,3895.869648,401.204305,1558.544003,616.477391,1272.099714,594.571134,NaN,NaN,6.642173e+04,4.785920e+05,1.687511e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.751450e+14,NaN,NaN,383.138518,187508.807659,0.561715,2.704164,0.069696,0.759285,0.050570,0.287505,0.175060,0.023094,0.049084,0.015436,0.025735,0.025102,0.085352,0.072890,0.282274,0.028212,0.056884,0.186399,0.055462,0.198785,1.789335,1.34603,1.005493,2.788884,2.249883,0.348870,0.392461,0.057713,0.128028,0.181207,2.050367e-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.101997,0.800616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,521.220212,NaN,NaN,NaN,1.469598e+06,25547.745861,47723.115729,NaN,NaN,8073.754689,NaN,NaN,10.060831
min,1.000000,NaN,NaN,NaN,5.962790e+09,NaN,NaN,NaN,NaN,1.880000e+02,1.920000e+02,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.455887e+09,NaN,NaN,-21514.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.513331,7.152706e-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.000000,NaN,NaN,NaN,2.600000e+02,300018.000000,119.000000,NaN,NaN,14066.000000,NaN,NaN,1933.000000
25%,162591.250000,NaN,NaN,NaN,1.000442e+14,NaN,NaN,NaN,NaN,1.656000e+04,2.172700e+04,NaN,NaN,NaN,NaN,6.300000e+01,3.300000e+01,8.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.894668e+11,NaN,NaN,-3.030000,162446.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.267654,7.627160e-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1653.000000,NaN,NaN,NaN,4.488300e+04,400347.000000,9622.000000,NaN,NaN,20758.000000,NaN,NaN,1950.000000
50%,325181.500000,NaN,NaN,NaN,1.000445e+14,NaN,NaN,NaN,NaN,2.888600e+04,3.735100e+04,NaN,NaN,NaN,NaN,1.950000e+02,9.100000e+01,43.000000,11.000000,7.000000,0.000000,2.000000,0.000000,1.000000,0.000000,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.111728e+14,NaN,NaN,-1.330000,324851.500000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.220902,1.274976e-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1913.000000,NaN,NaN,NaN,7.638600e+04,412307.000000,27110.000000,NaN,NaN,21342.000000,NaN,NaN,1956.000000
75%,487771.750000,NaN,NaN,NaN,1.000453e+14,NaN,NaN,NaN,NaN,6.622900e+04,1.037510e+05,NaN,NaN,NaN,NaN,6.790000e+02,3.060000e+02,172.000000,47.000000,32.000000,3.000000,10.000000,3.000000,8.000000,1.000000,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.705081e+14,NaN,NaN,1.600000,487321.750000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.00000,0.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,-0.147021,2.646930e-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2128.000000,NaN,NaN,NaN,1.003609e+06,412542.000000,83310.000000,NaN,NaN,29588.000000,NaN,NaN,1964.000000
max,650362.000000,NaN,NaN,NaN,1.015014e+16,NaN,NaN,NaN,NaN,3.312583e+07,3.545355e+07,NaN,NaN,NaN,NaN,3.007603e+06,1.656138e+06,795075.000000,753451.000000,676441.000000,200346.000000,711108.000000,234766.000000,207356.000000,306952.000000,NaN,NaN,1.634201e+07,1.230726e+08,3.674642e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.620769e+15,NaN,NaN,1226.350000,649482.000000,20.000000,75.000000,21.000000,27.000000,9.000000,20.000000,13.000000,4.000000,5.000000,2.000000,2.000000,4.000000,6.000000,5.000000,11.000000,4.000000,7.000000,13.000000,6.000000,1.000000,62.000000,62.00000,47.000000,61.000000,65.000000,21.000000,17.000000,3.000000,8.000000,4.043891,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2295.000000,NaN,NaN,NaN,9.269028e+06,456864.000000,166004.000000,NaN,NaN,94659.000000,NaN,NaN,1984.000000